---
- name: Set timezone to Asia/Seoul
  timezone:
    name: Asia/Seoul

- name: install Java and tools
  yum:
    name: ['dstat', 'java-1.8.0-openjdk', 'java-1.8.0-openjdk-devel', 'krb5-workstation', 'git']
    state: latest

- name: copy krb5 conf
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0644'
    backup: no