---
- name: download schema registry from web
  get_url:
    url: http://packages.confluent.io/archive/6.1/confluent-community-6.1.0.tar.gz
    dest: /opt/
    mode: '0600'

- name: unarchive confluent-community
  unarchive:
    src: /opt/confluent-community-6.1.0.tar.gz
    dest: /usr/local
    creates: /usr/local/confluent-6.1.0
    remote_src: yes

- name: setup link confluent
  file:
    path: /usr/local/confluent
    src: /usr/local/confluent-6.1.0
    state: link
    force: yes

- name: copy schema registry conf file
  copy:
    src: schema-registry.properties
    dest: /usr/local/confluent/etc/schema-registry/
    mode: '0644'
    backup: no

- name: copy schema registry in systemd
  copy:
    src: schema-registry.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: '0644'
    backup: no

- name: just force systemd to reload configs
  systemd:
    daemon_reload: yes

- name: make sure a service is running
  systemd:
    state: started
    name: schema-registry
    enabled: yes
